/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Book;
import Model.Review;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Juan
 */
public class BookReview extends javax.swing.JPanel  implements javax.swing.ListCellRenderer<Book> {

    /**
     * Creates new form BookReview
     */
    public BookReview() {
        initComponents();
    }
    
    // Pega este método completo en la clase
@Override
public Component getListCellRendererComponent(JList<? extends Book> list, Book book, int index, boolean isSelected, boolean cellHasFocus) {
    
    // --- Asigna los datos a tus componentes visuales ---
    titleLabel.setText("<html><b>" + book.getName() + "</b><br>" + book.getAuthorName() + "</html>");
    
    Review review = book.getReview(); // Obtenemos la reseña del libro
    if (review != null) {
        // Si hay reseña, la mostramos
        ratingLabel.setText(generateStars(review.getRating()));
        commentArea.setText("“" + review.getComment() + "”");
        commentArea.setVisible(true);
    } else {
        // Si no hay reseña, ocultamos los componentes
        ratingLabel.setText(""); // Sin estrellas
        commentArea.setText("");
        commentArea.setVisible(false);
    }

    // --- Maneja los colores de selección ---
    if (isSelected) {
        setBackground(list.getSelectionBackground());
    } else {
        setBackground(list.getBackground());
    }

    return this;
}

// Pega este método de utilidad también
private String generateStars(int rating) {
    StringBuilder stars = new StringBuilder();
    for (int i = 0; i < 5; i++) {
        if (i < rating) {
            stars.append("★"); // Estrella rellena
        } else {
            stars.append("☆"); // Estrella vacía
        }
    }
    return stars.toString();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        ratingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentArea = new javax.swing.JTextArea();

        titleLabel.setText("nombre del autor");

        ratingLabel.setText("estrellas");

        commentArea.setColumns(20);
        commentArea.setLineWrap(true);
        commentArea.setRows(5);
        commentArea.setWrapStyleWord(true);
        commentArea.setFocusable(false);
        jScrollPane1.setViewportView(commentArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(ratingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(ratingLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commentArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables


}
