package View;

import Controller.UserController;
import Model.User;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class Frame extends javax.swing.JFrame implements AuthView{

    private CardLayout cardLayout;
    private JPanel mainPanel;
    
    private LoginPanel loginPanel;
    private RegisterPanel registerPanel;

 
    
       public Frame(UserController userController) {
        // NO llames a initComponents() aquí todavía, lo vamos a modificar.

        // --- 1. Configuración básica del JFrame ---
        setTitle("Buenas Lecturas");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // --- 2. Establecer el CardLayout en el Content Pane del Frame ---
        cardLayout = new CardLayout();
        getContentPane().setLayout(cardLayout);

        // --- 3. Crear los paneles (esto está bien) ---
        loginPanel = new LoginPanel(this, userController);
        registerPanel = new RegisterPanel(this, userController);

        // --- 4. Añadir los paneles DIRECTAMENTE al Content Pane ---
        getContentPane().add(loginPanel, "LOGIN_PANEL");
        getContentPane().add(registerPanel, "REGISTER_PANEL");

        // --- 5. Ajustar el tamaño del Frame y hacerlo visible ---
        pack(); // Ajusta el tamaño del Frame al tamaño preferido de sus componentes.
        setLocationRelativeTo(null); // Centra la ventana.
        
         cardLayout.show(getContentPane(), "LOGIN_PANEL");
    }
    
    public void showPanel(String panelName){
        cardLayout.show(getContentPane(), panelName);
    }
    
    //Metodos de la interfaz
    @Override
    public void showErrorMessage(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void showSuccessMessage(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message, "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void navigateToHome(User user) {
        System.out.println("Navegando a la pantalla principal para el usuario: " + user.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents





    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
