/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BookController;
import Controller.UserController;
import Model.Book;
import Model.User;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class HomePanel extends javax.swing.JPanel {

   //Dependencias con el main frame y el user controller
   private Frame mainFrame;
   private UserController userController;
   private BookController bookController;
   private User currentUser;
   
   //Constructor del panel
    public HomePanel(Frame mainFrame, UserController userController, BookController bookController) {
        
        initComponents();
        
        this.mainFrame = mainFrame;
        this.userController = userController;
        this.bookController = bookController;
        
        // --- INICIALIZACIÓN DEL MODELO DE LA LISTA ---
        // Crea un modelo de lista que contendrá objetos Book.
        DefaultListModel<Book> initialModel = new DefaultListModel<>();
        
        // Asigna este modelo a tu JList.
        resultsList.setModel(initialModel);
        
        searchButon.addActionListener( new java.awt.event.ActionListener() {
           
            @Override
            public void actionPerformed(ActionEvent ae) {
                handleSearchClick();
            }
            
        });
        
        // Habilitar/deshabilitar el botón según la selección en la lista
        resultsList.addListSelectionListener(e -> {
            // Se habilita el botón solo si algo está seleccionado
            addToWhishlistButon.setEnabled(!resultsList.isSelectionEmpty());
        });
     
        // Acción para el botón "Añadir a Quiero Leer"
        addToWhishlistButon.addActionListener(e -> {
            // Obtenemos el libro seleccionado de la lista
            Book selectedBook = resultsList.getSelectedValue();
            if (selectedBook != null && currentUser != null) {
                // Llamamos al controlador de usuario para que haga el trabajo
                userController.addBookToWhishlist(currentUser, selectedBook);
            }
        });
        
    }
    
    private void handleSearchClick(){
        
        System.out.println("1. Clic en el botón de búsqueda detectado.");
        String query = buscarLibro.getText();
        System.out.println("   - Término de búsqueda: '" + query + "'"); // <-- AÑADE ESTO

        bookController.handleSearch(query);
    }
    
     public void showErrorMessage(String message) {
        // El propio panel muestra el popup de error.
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
     
     // ... dentro de la clase HomePanel ...


  public void updateResultsList(List<Book> books) {
    System.out.println("7. Dentro de updateResultsList. Actualizando el modelo con " + books.size() + " libros.");

    // CREAMOS UN MODELO NUEVO CADA VEZ. Es más simple y seguro.
    DefaultListModel<Book> newModel = new DefaultListModel<>();

    if (books != null && !books.isEmpty()) {
        // Llenamos el nuevo modelo con los libros.
        for (Book book : books) {
            newModel.addElement(book);
        }
    } else {
        // Para manejar el caso sin resultados, podríamos añadir un mensaje,
        // pero como el modelo es de <Book>, no podemos. Lo dejamos vacío.
        // Opcional: podrías mostrar un JLabel aparte con el mensaje "No se encontraron resultados".
    }

    // ASIGNAMOS EL NUEVO MODELO al JList.
    // Esto notificará automáticamente al JList que debe redibujarse.
    resultsList.setModel(newModel);
    
    // Opcional, como "seguro de vida" para forzar el repintado.
    // resultsList.revalidate();
    // resultsList.repaint();

    System.out.println("8. Modelo asignado al JList.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarLibro = new javax.swing.JTextField();
        searchButon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsList = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        addToWhishlistButon = new javax.swing.JButton();

        jLabel1.setText("Bienvenido a Buenas Lecturas");

        buscarLibro.setText("Buscar libro");
        buscarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarLibroMouseClicked(evt);
            }
        });

        searchButon.setText("Buscar");

        jScrollPane1.setViewportView(resultsList);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addToWhishlistButon.setText("Añadir a quiero leer");
        addToWhishlistButon.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addToWhishlistButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToWhishlistButon))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarLibroMouseClicked
        this.buscarLibro.setText("");
    }//GEN-LAST:event_buscarLibroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToWhishlistButon;
    private javax.swing.JTextField buscarLibro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Book> resultsList;
    private javax.swing.JButton searchButon;
    // End of variables declaration//GEN-END:variables
}
