/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UserController;

public class LoginPanel extends javax.swing.JPanel {

    //Dependencias
    private final Frame mainFrame;
    private final UserController userController;
    
    //Constructor del panel
    public LoginPanel(Frame mainFrame, UserController userController) {
        initComponents();
        this.mainFrame = mainFrame;
        this.userController = userController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userEmail = new javax.swing.JTextField();
        userPassword = new javax.swing.JTextField();
        loginButon = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        registerButon = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setMinimumSize(new java.awt.Dimension(891, 639));
        setPreferredSize(new java.awt.Dimension(891, 639));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("Formulario de Inicio De Sesión");

        userEmail.setBackground(new java.awt.Color(255, 243, 232));
        userEmail.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        userEmail.setText("nombre@mail.com");
        userEmail.setToolTipText("");
        userEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userEmailMouseClicked(evt);
            }
        });

        userPassword.setBackground(new java.awt.Color(255, 243, 232));
        userPassword.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        userPassword.setText("Contraseña");
        userPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userPasswordMouseClicked(evt);
            }
        });

        loginButon.setBackground(new java.awt.Color(255, 243, 232));
        loginButon.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        loginButon.setText("Iniciar Sesión");
        loginButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButonActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 204, 153));
        jTextField3.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextField3.setText("No tienes usuario?");
        jTextField3.setBorder(null);

        registerButon.setBackground(new java.awt.Color(255, 243, 232));
        registerButon.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        registerButon.setText("Registrate acá");
        registerButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerButon))
                    .addComponent(userEmail)
                    .addComponent(userPassword)
                    .addComponent(loginButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButon))
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButonActionPerformed
        userController.handleLogin(userEmail.getText(), userPassword.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_loginButonActionPerformed

    private void registerButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButonActionPerformed

       mainFrame.showPanel("REGISTER_PANEL");
    }//GEN-LAST:event_registerButonActionPerformed

    private void userEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userEmailMouseClicked
      userEmail.setText("");
    }//GEN-LAST:event_userEmailMouseClicked

    private void userPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPasswordMouseClicked
      userPassword.setText("");
    }//GEN-LAST:event_userPasswordMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton loginButon;
    private javax.swing.JButton registerButon;
    private javax.swing.JTextField userEmail;
    private javax.swing.JTextField userPassword;
    // End of variables declaration//GEN-END:variables
}
