/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BookController;
import Model.Book;
import Model.Review;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class ReviewDialog extends javax.swing.JDialog {

    
    private final Book book;
    private final BookController bookController;
    
    
    public ReviewDialog(java.awt.Frame parent, Book book, BookController bookController) {
    super(parent, true); // true para hacerlo modal
    this.book = book;
    this.bookController = bookController;
    
    initComponents(); // Esta línea ya existe
    
    this.setTitle("Reseña para: " + book.getName());
    populateData(); // Llena el formulario con datos existentes si los hay
    setLocationRelativeTo(parent); // Centra el diálogo
}
    
    // Pega estos métodos en tu clase

// Si el libro ya tiene una reseña, la cargamos en el formulario
private void populateData() {
    Review existingReview = book.getReview();
    if (existingReview != null) {
        ratingSlider.setValue(existingReview.getRating());
        commentTextArea.setText(existingReview.getComment());
    }
}

private void saveReview() {
    int rating = ratingSlider.getValue();
    String comment = commentTextArea.getText();

    if (comment == null || comment.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "El comentario no puede estar vacío.", "Error de validación", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Llamamos al método del controlador que ya hemos creado
    bookController.saveReview(book, rating, comment);

    // Cerramos el diálogo
    dispose();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingSlider = new javax.swing.JSlider();
        ScrollPane = new javax.swing.JScrollPane();
        commentTextArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        ratingSlider.setBackground(new java.awt.Color(255, 255, 255));
        ratingSlider.setForeground(new java.awt.Color(0, 0, 0));
        ratingSlider.setMajorTickSpacing(1);
        ratingSlider.setMaximum(5);
        ratingSlider.setMinimum(1);
        ratingSlider.setPaintLabels(true);
        ratingSlider.setPaintTicks(true);
        ratingSlider.setSnapToTicks(true);
        ratingSlider.setValue(3);

        commentTextArea.setColumns(20);
        commentTextArea.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        commentTextArea.setRows(5);
        ScrollPane.setViewportView(commentTextArea);

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        saveButton.setText("Guardar ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(54, 54, 54)
                        .addComponent(saveButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ratingSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ScrollPane)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveReview();
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea commentTextArea;
    private javax.swing.JSlider ratingSlider;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
